export const sources = [
  {id:'MIT-D',name:'MIT Course 8 degree requirements',url:'https://catalog.mit.edu/degree-charts/physics-course-8/',note:'Current catalogue accessed 23 September 2026. Focused option used as a depth reference; flexible option confirms that legitimate physics routes differ. MIT units are not LibraUni credits.'},
  {id:'MIT-S',name:'MIT physics subject descriptions',url:'https://catalog.mit.edu/subjects/8/',note:'Current catalogue accessed 23 September 2026. Topic and prerequisite descriptions support this first subject-level comparison, not a complete assessment-by-assessment equivalence audit.'},
  {id:'MIT-C1',name:'MIT 18.01SC calculus syllabus',url:'https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/pages/syllabus/',note:'Historical 2010 open teaching syllabus, accessed 23 September 2026. Used for explicit calculus-entry expectations and scope, not current degree regulations.'},
  {id:'MIT-C2',name:'MIT 18.02SC multivariable calculus syllabus',url:'https://ocw.mit.edu/courses/18-02sc-multivariable-calculus-fall-2010/pages/syllabus/',note:'Historical 2010 open teaching syllabus, accessed 23 September 2026. Used to separate elementary vector fluency from later multivariable methods.'},
  {id:'IC-D',name:'Imperial F300 Physics BSc programme specification, 2025–26',url:'https://www.imperial.ac.uk/media/imperial-college/study/programme-specifications/physics/25x2f26/F300-BSc-Physics-2025-26.pdf',note:'Dated programme reference. Indexed official tables retrieved on 23 September 2026; direct PDF retrieval was blocked. Do not treat this as a fully read specification or a verified 2026–27 specification.'},
  {id:'IC-P',name:'Imperial Physics BSc published course structure',url:'https://www.imperial.ac.uk/study/courses/undergraduate/physics-bsc/',note:'Official indexed course content retrieved on 23 September 2026; page advertised 2027 entry. Used for listed subjects and core/optional distinctions. Direct fetch was blocked. Do not silently merge entry-year regulations.'},
  {id:'OU-F',name:'OU Discovering mathematics (MU123)',url:'https://www.open.ac.uk/courses/qualifications/details/mu123/',note:'Foundations scope reference accessed 23 September 2026. LibraUni uses original units and examples; no OU module equivalence is claimed.'},
];

// Stage 1 outcome-level proposal: /programme/stage-1/map/ (25 September 2026).
// No unit-level gap is closed by this proposal.
// Proposed destinations, not assertions that content or lessons already exist.
export const coverage = [
  ['C01','Precalculus readiness','MIT-C1; OU-F','M100 U01–U10; M101 entry','Revised outline','Algebra, functions, geometry and trigonometry are entry-readiness requirements. M100 offers optional preparation outside the degree; learners who skip it must demonstrate readiness. M101 should diagnose/retrieve these tools rather than repeat their full teaching.'],
  ['C02','Calculus, series and mathematical reasoning','MIT-C1','M101 → M102','Pending','Module-level proposal: M101-O1/O2/O5 introduce calculus and checks; M102-O2 extends integration and series. Unit/assessment mapping and hours remain pending. M100 intentionally stops before calculus.'],
  ['C03','Linear algebra and multivariable methods','MIT-C2; MIT-S (8.05)','M101/M102 → M201','Pending','Module-level proposal: M101-O3/O4 introduce vectors/matrices; M102-O3 extends eigenproblems. Multivariable/vector calculus remains M201; unit/assessment mapping is pending. M100 U10 is only geometric preparation.'],
  ['C04','Differential equations and transform methods','MIT-D (18.03); IC-D','M102 → M201 → P201/P301','Pending','M102-O4/O5 propose introductory analytic/numerical ODEs; M201 retains transforms and PDEs. Track boundary/initial conditions and mathematical depth; establish when physics units may use them.'],
  ['C05','Newtonian mechanics and relativity','MIT-S (8.01, 8.033); IC-D','P101 → P201','Pending','Specify rotation, angular momentum, central forces, frames and relativistic reasoning rather than relying on the word mechanics. Introductory mathematics is not mechanics coverage.'],
  ['C06','Analytical mechanics','MIT-D (8.223)','P201 with M201 support; destination needs review','Gap to resolve','The blueprint does not explicitly allocate variational reasoning, generalised coordinates or Lagrangian/Hamiltonian methods. Decide a core minimum and its hours before approving P201; advanced extensions can remain optional.'],
  ['C07','Oscillations, waves and optics','MIT-S (8.03); IC-D','P101 → P201 → P301','Pending','Require outcomes for coupled behaviour, resonance, propagation and optical interference/diffraction. Distinguish introductory pictures from quantitative treatment.'],
  ['C08','Electromagnetism and elementary circuits','MIT-S (8.02, 8.07); IC-D','P101 → P201 → P301; X201 applications','Pending','Trace fields, potentials, induction, circuit reasoning and radiation across increasing mathematical depth; specify the first teaching and later application of each.'],
  ['C09','Thermodynamics and statistical physics','MIT-D (8.044); IC-D','P201 core; P303 deeper option','Depth to resolve','Set an explicit compulsory statistical foundation with probability support. A later elective cannot be the only home for essential thermal/statistical reasoning.'],
  ['C10','Quantum and atomic physics','MIT-D (8.04–8.06); IC-D','P201 → P302','Depth to resolve','The broad quantum label does not establish how much formalism, approximation, angular momentum, atomic structure and scattering fits. MIT’s extended sequence is a depth reference, not a workload equivalence promise.'],
  ['C11','Solid-state foundations','IC-P; MIT-S (8.231)','P201/P302 core allocation to decide; P303 optional depth','Gap to resolve','Imperial lists solid state in its core. Define a compulsory introductory outcome set and budget; leaving the whole subject to P303 would leave other routes without that foundation.'],
  ['C12','Nuclear and particle physics','IC-P; MIT-S (8.276)','P201/P302 allocation to decide','Gap to resolve','No explicit unit-level home is yet confirmed. Reserve a decision on nuclear structure/decay, interactions and particle evidence; review whether the existing module capacities suffice.'],
  ['C13','Probability, uncertainty and data inference','MIT-S (8.044); IC-D','P101/A101 → X201 and P201; mathematical support M102/M201','Gap to resolve','Optional M100 supplies elementary preparation but cannot be the sole home of required degree outcomes. The Stage 1 map proposes P101-O5 for introductory uncertainty, A101 application and M102-O6 for elementary probability. These outcome-level homes still need units, assessment evidence and a capacity check; the gap remains open. Allocate conditional/continuous probability, distributions, propagation, fitting and evidence-based interpretation before they are required.'],
  ['C14','Scientific computing and numerical validation','MIT-S (8.006); IC-P','M100 preparation → A101/P101 → M201/X201 → project; C301 extension','Pending','The Stage 1 map proposes P101-O6 as required shared Python teaching, with M101 applications and M102/A101 extensions; unit-level ordering remains pending. M100 1.1 has approved block scopes with 48 integrated computing hours: independent foundations, U08–U10 suggestion/trace critique, and U12 bounded hands-on agent practice. TMA01/02 and EMA A provide independent coding evidence; EMA C supplies code for critique. Free tool feasibility and detailed rubrics remain release gates. Semester 2 A101 U05–U10 provisionally outline calibrated data, spectral/temporal checks and a reproducible investigation with TMA/EMA evidence; teaching remains unavailable. Require reproducibility, convergence/error checks and model validation. Making plots is only a starting skill; software output is not independent physical evidence.'],
  ['C15','Laboratory practice, instrumentation and teamwork','MIT-D (8.13/8.14); IC-D; IC-P','P101/X201/R300; physical-access decision outstanding','Known limitation','A101 U04/U05/U07/U10 outline observing choices, detector data, variability and an investigation. Simulation and measured-data analysis can support design and interpretation but cannot certify apparatus handling, instrument troubleshooting or real collaboration. Preserve these unfulfilled outcomes explicitly.'],
  ['C16','Research, communication and synoptic reasoning','MIT-D; IC-P','All modules → X201/R300','Pending','Map writing, source criticism, oral explanation and cross-topic problem solving to assessed evidence. Optional M100 O7 maps to explained TMA solutions, the U12 formative investigation and EMA A/B/C; its planned evidence does not establish achieved mastery. P101 must establish the required degree-level starting outcomes; A101 A6 maps to TMAs and an EMA defence.'],
  ['C17','Specialist directions','IC-P; MIT-D','A101 U01–U10 introductory astronomy; Stage 3 options and additional certificates','Selective by design','Astrophysics, cosmology, fluids, advanced dynamics and matter routes remain choices. The programme does not reproduce the union of two universities’ elective catalogues.'],
  ['C18','Broader institutional requirements','MIT-D; IC-D','Outside this physics-content comparison','Scope boundary','General education, institution-specific breadth requirements and campus activities are not claimed as part of LibraUni’s physics curriculum. Scientific context and ethics still need explicit consideration within our modules.'],
];

export const gaps = [
  {id:'G01',title:'Make the missing subject homes explicit',rows:['C06','C11','C12','C13'],decision:'When designing the relevant modules, specify compulsory outcomes, units, assessment and hours for analytical mechanics, solid-state basics, nuclear/particle physics and probability/data methods. Until then these gaps remain open.'},
  {id:'G02',title:'Protect depth within the fixed credit budget',rows:['C09','C10'],decision:'Audit P201’s 600 hours and P302’s 300 hours before adding topic commitments. If breadth and depth do not fit, propose a visible reallocation or an extension; do not quietly increase required work or claim every benchmark outcome is covered.'},
  {id:'G03',title:'State the practical boundary honestly',rows:['C15'],decision:'Separate outcomes demonstrable through simulations/data from outcomes requiring real apparatus or collaborators. Investigate free opportunities later; do not certify unavailable experiences.'},
  {id:'G04',title:'Finish the evidence audit progressively',rows:['C02','C03','C04','C05','C07','C08','C14','C16','C17'],decision:'Retrieve detailed authoritative syllabi and assessments for the subject being designed. Imperial’s accessible indexed material supports a first comparison only; fuller module-level verification remains required.'},
];
