// Original design proposal; no lessons, answers or learner records.
export const block1 = {
 status:'Scope and TMA 01 Python component approved · detailed materials pending',
 purpose:'Calculate reliably, express relationships precisely and check short programs independently before moving to graphs and functions.',
 workloadLabels:['Explanation & worked examples','Mathematical practice','Python practice','Physical application','Retrieval & checkpoints'],
 units:[
  {id:'U01',hours:[4,5,4,2,1],
   sequence:['Signed quantities, number lines and order of operations.','Fractions, decimals, percentages and exact versus approximate answers.','Estimation, rounding and clear written reasoning.','Notebook cells, arithmetic operators, numeric types and named values; predict before executing.'],
   practice:'Move from single-step calculations to mixed expressions, then explain and repair a plausible wrong solution. Revisit signs and fractions in later units rather than assuming one successful exercise establishes fluency.',
   investigation:'Compare a short physical timescale with a much longer one using supplied values. Estimate first, calculate second, and explain whether the displayed precision is justified. Scientific notation is introduced fully in U02.',
   evidence:'Without a generated solution, calculate a mixed fraction/sign expression, defend an estimate and correct an order-of-operations error. Write and explain the corresponding short Python calculation.',
   pitfalls:'Confusing a negative value with subtraction; applying operations left to right indiscriminately; treating every displayed decimal as meaningful. Python assignment is not mathematical equality.',
   visuals:'Number line for signed quantities; annotated expression showing operation order; exact value and rounded display side by side.',
   forward:'U02 uses reliable arithmetic for powers, compound units and scale. Preserve the distinction between a quantity, its numerical value and the chosen unit.'},
  {id:'U02',hours:[4,6,3,3,2],
   sequence:['Powers, roots and the restrictions on real-number operations.','Scientific notation, orders of magnitude and SI prefixes.','Ratios, direct/inverse proportionality and compound-unit conversion.','Dimensions and scale factors; distinguish a consistency check from evidence that a physical law is correct.'],
   practice:'Alternate abstract power manipulation with unit-bearing calculations. Include a conversion involving squared units and an error caused by mixing units. The two checkpoint hours include the existing one-hour iCMA 41.',
   investigation:'Use a supplied distance–speed–time relation to compare travel times, then a supplied inverse-square relation to predict a change in intensity. State what stays fixed and test whether the change has the expected direction.',
   evidence:'Convert a compound quantity, predict a scaling factor before calculation and explain why a dimensionally compatible relation can still be physically wrong. Write a short named-variable calculation and check it against an estimate.',
   pitfalls:'Scaling an area as though it were a length; confusing an exponent with a multiplier; accepting Python numbers as automatically unit-aware; assuming dimensional compatibility proves correctness.',
   visuals:'Conversion chains with cancelling units; comparative length/area scaling diagram; order-of-magnitude ladder.',
   forward:'U03 turns quantitative relations into expressions. Functions and inverse relationships return in Block 2; logarithmic scales wait until U09.'},
  {id:'U03',hours:[5,8,4,3,2],
   sequence:['Symbols as quantities: variables, constants, parameters and substitution.','Collecting terms, brackets, distributivity and simple factorisation.','Algebraic fractions, cancellation and excluded values.','Identities versus equations; counterexamples; Boolean comparisons and short if/else checks.'],
   practice:'Translate between words and symbols, compare expressions, identify invalid transformations and explain a counterexample. Introduce conditions through simple numerical restrictions; general symbolic solvers are not required.',
   investigation:'Interpret a supplied measurement relation with an offset and a scale factor. Track the role and units of each symbol, and diagnose a calculation that applies the offset in the wrong place.',
   evidence:'Simplify an expression with a stated domain, reject invalid cancellation and explain why several matching numerical tests do not prove an identity. Write a small condition that prevents an invalid calculation.',
   pitfalls:'Treating unlike terms as combinable; cancelling across addition; losing excluded inputs; confusing = and ==; assuming agreement at sampled values constitutes proof.',
   visuals:'Expression structure annotated by role; an equivalence chain with restrictions kept visible; a small decision diagram for a domain check.',
   forward:'U04 changes an expression into a problem with unknowns. U06 later formalises functions, inputs, outputs and domains; the current measurement context must not assume that teaching has occurred.'},
  {id:'U04',hours:[5,10,3,4,2],
   sequence:['Solve linear equations while preserving equality.','Change the subject of a formula; retain restrictions on division and reversible steps.','Solve two simultaneous linear equations; recognise inconsistent and dependent cases.','Solve linear inequalities, represent intervals and reverse the sign correctly when multiplying by a negative.','Use lists, short loops and elementary assertions to check selected candidate values.'],
   practice:'Choose a method, show its justification, substitute into the original relation and interpret the answer. Mix earlier fractions, units and algebra into later tasks. Keep code short enough to explain line by line.',
   investigation:'Infer two unknown quantities from two supplied measurement relations, then examine whether the result satisfies a stated bound. All required physical assumptions are supplied; operational procedures or safety decisions are outside scope.',
   evidence:'Rearrange a formula, solve a small system and an inequality, preserving all restrictions. Independently write a loop over candidate values and explain what its checks do—and do not—establish.',
   pitfalls:'Dividing by an expression that could be zero; reversing an inequality unnecessarily or failing to reverse it; treating an underdetermined system as a unique answer; accepting a numerical check instead of the algebraic argument.',
   visuals:'Balance interpretation of equivalent operations; interval/number-line diagrams; two independent relations represented as labelled information constraints. Graphical solution follows in U05.',
   forward:'U05 represents the same linear relationships graphically. TMA 01 samples independent calculation, algebra, interpretation and short code before that transition.'},
 ],
 assessment:'Retain iCMA 41 after U02 within its hours. Agreed TMA 01 design retains six hours: 4.5 hours written reasoning, 1 hour of short learner-written Python and 0.5 hours preparing/checking submission files. The Python task replaces part of the existing workload; it is not an extra assignment. It samples calculations, conditions and checking, not functions, arrays or plotting that have not yet been taught. Documentation is allowed; generated solutions are excluded from this independent evidence. Exact questions and scoring remain to be authored.',
 readiness:'Use a short retrieval task inside each unit’s existing checkpoint budget. Confident performance can justify a tutor-agreed shorter refresher path; it does not automatically award full-module credit or mark units complete. Required practice is purposeful and finite; clearly labelled backup exercises address specific gaps. Record extra remedial time honestly if needed. No separate diagnostic or timed speed test is introduced by this proposal.',
 coherence:'Block 1 provides the calculation and algebra base for Block 2. It begins exit capabilities E1, E2 and E4 and rehearses E5 communication/checking; it does not complete the whole exit standard. AI/agent operation remains later work, after learner-written foundations. M100 prepares entry to M101/P101 but is outside degree credits and cannot replace their required outcomes.',
 limitations:'These are original workload estimates, not an exact OU timetable or measured learner timings. The retained calendar places U01–U04 in reference weeks 1–9. Their 80 hours plus 6 hours orientation and 6 hours TMA 01 total 92 hours in that window; feedback has a separate existing allocation in week 10. Assessment boundaries need not coincide exactly with block boundaries. No schedule version, saved dates or module total changes.',
};
