// Module-level scope approved 26 September 2026; blocks, units and teaching require separate review.
export const stage1Map={version:'1.0',date:'26 September 2026',status:'Module-level scope approved · detailed design pending',
 stages:[
 ['Stage 1 · 120 credits / 1,200 hours','Use elementary calculus, vector/matrix methods, complex numbers and introductory ODEs; solve bounded introductory physics problems and conduct a reproducible small data investigation.','M101/P101 then M102/A101; quantitative foundations before formal field, quantum and statistical methods.'],
 ['Stage 2 · 120 credits / 1,200 hours','Connect core physical theories, more advanced mathematical methods and validated experimental/computational investigations.','Provisional P201/M201/X201. Explicit compulsory homes and capacity remain to be settled for analytical mechanics, thermal/statistical depth, solid-state and nuclear/particle foundations.'],
 ['Stage 3 · 120 credits / 1,200 hours','Use advanced electromagnetic and quantum models, develop one specialist direction and defend an independent investigation.','Provisional P301/P302 + one option + R300. Project requires subject readiness and X201 investigative skills. Specialist options cannot supply the only compulsory foundation.'],
 ],
 entry:'Before Semester 1: manipulate fractions and signed quantities, rearrange elementary equations, use powers/logarithms and basic trigonometry, interpret graphs and units. Diagnose these skills without assuming them from qualifications. M100 or scoped refreshers can supply preparation. No calculus or prior Python proficiency is required for entry; P101 explicitly introduces the shared computing workflow.',
 modules:[
 {code:'LU-M101',anchor:'m101',role:'Mathematical language for quantitative physics',entry:'Stage 1 mathematical readiness; no calculus or Python mastery assumed. P101 is concurrent, not a prerequisite already completed.',
 outcomes:[
 ['M101-O1','Explain limits and derivatives as local behaviour and rates; differentiate elementary functions and justify the method used.'],
 ['M101-O2','Interpret definite integration as accumulation and apply the fundamental theorem; calculate elementary integrals with units and checks.'],
 ['M101-O3','Use coordinate vectors, magnitudes, scalar products and elementary vector products to represent and resolve physical quantities.'],
 ['M101-O4','Use matrices as linear transformations and solve small linear systems, recognising when a solution is not unique.'],
 ['M101-O5','Use elementary approximations and numerical derivative/integral checks; distinguish a numerical check from a proof.'],
 ['M101-O6','Present a coherent mathematical argument and explain short Python calculations using the shared foundation introduced in P101.'],
 ],
 owns:'First degree teaching of single-variable calculus, coordinate vector algebra and introductory matrix methods. Retrieve precalculus where needed without repeating the full bridge. P101 owns the physical interpretation of force, work and measurement.',
 boundary:'M102 owns systematic complex-number methods, series, further linear algebra and introductory ODE solution methods. M201 owns full multivariable/vector calculus, transforms and PDE methods. Numerical checks do not replace analytical working.',
 evidence:'TMAs combine handwritten/scanned reasoning, physical interpretation and short explained computational checks. iCMAs provide feedback within study hours. Proposed final written exam samples independent mathematical reasoning; format and marking remain to be designed.',
 final:'Final written examination',computing:'Apply scalar calculations, functions and plots after P101 foundation handover. Introduce finite-difference and quadrature checks as mathematical methods, including changes of step size.',handover:'M101-O1/O2 support later P101 rate/work applications; O3 supports force resolution; O1–O5 prepare M102; O2/O3/O6 support astronomical calculations and plots in A101.'},
 {code:'LU-P101',anchor:'p101',role:'Physical reasoning, measurement and scientific computing',entry:'Stage 1 mathematical readiness and concurrent M101. Begin with algebraic/graphical problems; do not require calculus before its M101 teaching.',
 outcomes:[
 ['P101-O1','Construct and test elementary motion/force models using diagrams, Newtonian reasoning, units and stated assumptions.'],
 ['P101-O2','Use momentum and energy balances in simple systems, distinguishing work, heat and conserved quantities.'],
 ['P101-O3','Relate simple oscillation, wave and light descriptions to observations; use frequency, wavelength and propagation relations.'],
 ['P101-O4','Explain introductory field/potential and simple DC-circuit models and use microscopic/atomic pictures with explicit limits; distinguish qualitative introduction from formal theory.'],
 ['P101-O5','Plan a small investigation, interpret repeated measurements and instrument resolution, distinguish random/systematic effects and justify reported precision and limitations.'],
 ['P101-O6','Write and explain small Python programs with variables, conditions, loops and functions; load small tables, use basic arrays, plot labelled data and save a clean reproducible notebook.'],
 ['P101-O7','Communicate a physical conclusion supported by calculations/data and traceable sources; explain simple numerical/model checks and disclose assistance.'],
 ],
 owns:'First shared degree teaching of scientific Python and notebook practice, measurement conventions, elementary descriptive statistics and uncertainty reasoning. Mechanics and conservation provide the main quantitative spine; waves/light, simple circuits and microscopic pictures broaden physical context.',
 boundary:'Not a compressed complete undergraduate physics survey. Relativistic mechanics, formal quantum/statistical mechanics, full electromagnetism and quantitative solid-state/nuclear/particle foundations require later core allocations. Introductory mentions do not close coverage gaps. P101 does not take over M101 calculus derivations.',
 evidence:'TMAs sample explained problem solving, measurement/data critique and independent code. Proposed EMA combines a bounded investigation with written conceptual/quantitative checks so a project cannot omit whole outcome areas. Embedded iCMAs support retrieval.',
 final:'EMA',computing:'Explicitly teach the Python foundation to entrants who skipped M100; offer a demonstrated-skill retrieval route for prepared learners. Separate independent code from later assisted experiments. Use free local tools and small data; no paid AI or telescope required.',handover:'P101-O5/O6/O7 form the practical entry contract for A101 and the starting evidence strand for X201. O1–O4 prepare later core physics; they do not replace P201.'},
 {code:'LU-M102',anchor:'m102',role:'Mathematical structures, approximation and change',entry:'M101-O1–O6 and P101-O6 computing foundation. A101 is concurrent; neither module may require an unfinished result from the other to begin.',
 outcomes:[
 ['M102-O1','Use complex arithmetic, polar/exponential representations and elementary identities to represent oscillatory quantities.'],
 ['M102-O2','Apply selected further integration techniques and series/Taylor approximations with explicit validity and truncation considerations.'],
 ['M102-O3','Solve small eigenvalue/eigenvector problems and use basis changes and orthogonality in finite-dimensional examples.'],
 ['M102-O4','Solve introductory separable and linear first-order ODEs and constant-coefficient second-order ODEs with initial conditions; check solutions by substitution.'],
 ['M102-O5','Use an elementary numerical ODE method, compare it with a known solution and investigate step-size error and limitations.'],
 ['M102-O6','Use probability rules, conditional probability, expectation and variance in elementary finite models and interpret a simple continuous density with single-variable integration.'],
 ['M102-O7','Present analytical and computational reasoning with explicit assumptions, error checks and appropriate notation.'],
 ],
 owns:'Further mathematical development after M101; first systematic complex-number, series, eigenproblem and ODE treatment. Provide an explicit mathematical probability foundation supporting later statistical physics and inference.',
 boundary:'Full multivariable/vector calculus, Fourier/PDE methods and general ODE theory remain M201. Inference, parameter estimation and extensive distribution theory require X201/M201/P201 coordination. Probability is a deliberate capacity reservation, not a claim that a complete statistics course fits here.',
 evidence:'TMAs sample analytical derivations, approximation, probability reasoning and independent numerical checks. Embedded iCMAs test prerequisites and feedback. Proposed final written exam requires coverage across core outcomes, with practical code assessed separately in TMAs.',
 final:'Final written examination',computing:'Extend established functions/arrays into small numerical experiments; compare analytic and numerical results, vary a resolution parameter and explain failure cases. Do not repeat P101 Python induction.',handover:'O1–O5/O7 prepare mathematical work in M201/P201; O6 supports later statistical reasoning. A101 core activities must remain viable with Semester 1 prerequisites; any M102-linked enrichment is explicitly labelled and timed.'},
 {code:'LU-A101',anchor:'a101',role:'Astronomical evidence and reproducible investigation',entry:'M101 calculus/vector/numerical foundations and P101 light, measurement, Python and reporting outcomes. Exact outcome-to-unit links await its block/unit review; no compulsory M100 prerequisite.',
 outcomes:[
 ['A1','Place observations in astronomical context while distinguishing apparent position, physical scale and inference.'],
 ['A2','Explain how detector response, sampling, background and selection affect images, spectra and light curves.'],
 ['A3','Use introductory flux, spectral-shift, transit, parallax and magnitude models with units, assumptions and plausibility checks.'],
 ['A4','Form a bounded astronomical question, analyse a small documented dataset and compare evidence with model predictions.'],
 ['A5','Own and validate the computation: explain code, preserve provenance, rerun cleanly and audit any assistance.'],
 ['A6','Communicate results with labelled figures, uncertainty/limitations and a defensible account of what the evidence establishes.'],
 ],
 owns:'Application and extension of Semester 1 skills to observational astronomy: calibrated data, spectra, time series and distance/brightness inference. Retain existing A1–A6 identifiers; these are concise module-level restatements, not approval of revised units.',
 boundary:'No repeat of full Python or arithmetic foundations. No full stellar-structure, galactic-dynamics or cosmology derivation course; later specialist options retain those roles. Revised ten-unit version0.3 remains proposed within approved blocks, with exact Semester 1 prerequisites and reduced introductory duplication.',
 evidence:'Retain the existing provisional three-TMA and one-EMA model for review: evidence/provenance, calibration, signals/distance, then a reproducible investigation and defence with cross-outcome checks. iCMAs remain embedded.',
 final:'EMA',computing:'Deeper notebook investigations with small arrays/tables, calibrated plots, units, checks against subsets/limiting cases and a documented environment. Free datasets and tools need verification before teaching release. Optional observing equipment may enrich a later activity; required outcomes retain a free route.',handover:'Prepare X201 investigation design/validation and later astronomy/project choices. An introductory astronomy result is not evidence that advanced stellar/cosmological prerequisites have been met.'},
 ],
 workload:[['Unit study and embedded practice/iCMAs',240],['Orientation and module-specific workflow',6],['TMAs (provisional three × six hours)',18],['Final assessment, including required preparation/submission tasks',18],['Revision',12],['Feedback and follow-up',6]],
 ownership:[
 ['Basic Python, notebook execution, functions, arrays and plots','P101-O6: shared first teaching','M101 applies after staged handover; M102/A101 extend. M100 offers earlier preparation only.'],
 ['Calculus, vectors and elementary matrices','M101-O1–O5','P101 applications follow teaching; M102 extends formal methods.'],
 ['Measurement, elementary uncertainty and descriptive data','P101-O5','A101 applies to observations; M102-O6 supplies probability foundations; X201 deepens inference/propagation.'],
 ['Complex numbers, series, eigenproblems and ODEs','M102-O1–O5','M201/P201 extend; A101 must not silently assume concurrent material before availability.'],
 ['Physical models and meaning of quantities','P101-O1–O4','M101/M102 use explicitly supplied contexts; A101 owns astronomical model assumptions.'],
 ['Reproducibility, evidence and communication','P101-O6/O7 establishes; every module assesses its own use','A101 develops sustained investigation; X201/R300 later require broader independence.'],
 ],
 interfaces:[
 ['H01 · Python induction','P101-O6 → M101-O6','M101 begins with written/numerical mathematical work; independent coding tasks wait for P101’s scalar/function foundation. Shared induction is budgeted in P101, not charged twice. Unit-level timing still required.'],
 ['H02 · Vectors and rates','M101-O3/O1/O2 → P101-O1/O2','Force resolution follows vector teaching; calculus-based velocity/work follow derivative/integral teaching. Earlier P101 tasks use explicit algebraic and graphical models.'],
 ['H03 · Semester 2 entry','M101-O1–O6 + P101-O3/O5/O6/O7 → M102/A101','Check outcome readiness rather than elapsed calendar dates. A101 assumes an established Python/measurement workflow; brief retrieval is not a second foundation course.'],
 ['H04 · Concurrent Semester 2 work','M102 → A101 only when explicitly scheduled','No required core A101 dependency on late M102 ODE/eigenproblem teaching. If a proposed investigation needs it, move the activity after teaching or revise the requirement visibly; do not add hidden mathematics.'],
 ['H05 · Stage 2 mathematics','M101/M102 → M201/P201','Stage 2 needs a shared ordering plan: P201 may use advanced vector calculus only after M201 supplies it. Our Stage 1 mathematics does not claim that full machinery.'],
 ['H06 · Stage 2 investigation','P101/A101 → X201','Entry evidence includes documented data, explained code, units, model checks and a defended limitation. Physical apparatus and collaboration require separate opportunities/evidence.'],
 ],
 sources:[
 ['OU R51','https://www.open.ac.uk/courses/physics/degrees/bsc-physics-r51/','Retrieved 25 September 2026. Supports staged modular architecture and distinct later core, practical and specialist roles. LibraUni’s fixed Stage 1 is its own adaptation, not an OU route equivalence.'],
 ['OU MST124','https://www.open.ac.uk/courses/modules/mst124/','Retrieved 25 September 2026. Supports revision/communication/computing embedded in mathematics and progression to MST125. Detailed topic lists are omitted in the retrieved page text; no full syllabus or weekly timetable adoption claimed.'],
 ['OU MST125','https://www.open.ac.uk/courses/modules/mst125/','Retrieved 25 September 2026. Further mathematics follows MST124; includes an exam. Assessment naming is retained, but LibraUni formats/budgets are proposals, not copied OU arrangements.'],
 ['OU SM123','https://www.open.ac.uk/courses/modules/sm123/','Retrieved 25 September 2026. Physics, space, Python and practical work share a module. LibraUni P101 deliberately prioritises a quantitative foundation; mentioning modern topics cannot discharge later core depth.'],
 ['MIT Course 8','https://catalog.mit.edu/degree-charts/physics-course-8/','Retrieved 25 September 2026. Degree-depth check: ODEs, waves, relativity, quantum/statistical study, experimental work and advanced mechanics. MIT units are not LibraUni credits; no first-year or whole-degree equivalence inferred.'],
 ['MIT 18.01SC','https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/pages/syllabus/','Historical 2010 open syllabus retrieved 25 September 2026; single-variable calculus scope reference. Detailed outcome/assessment comparisons remain for module design.'],
 ['Imperial Physics BSc (2027 entry)','https://www.imperial.ac.uk/study/courses/undergraduate/2027/physics-bsc/','Official search-indexed content retrieved 25 September 2026 identifies mechanics/relativity and statistics of measurement/project work. Direct page retrieval failed. This is a limited breadth check, not a fully read specification or detailed equivalence audit.'],
 ],
};
